### ISSUE TITLE
header appearance problem

### ISSUE THREAD

**Issue by XinLi0111** [rcvd/logseq-bear-theme#18]
![](https://user-images.githubusercontent.com/31495943/145819131-a2690ba5-5fd8-4b38-9358-31dcc6d88568.png)

see issue in Logseq repo, https://github.com/logseq/logseq/issues/3447

**Comment by rcvd** [comment]
I can't reproduce the problem. The search panel being aligned to the bottom seems to be LogSeq default behaviour (and is correct for mobile devices because you can reach it more easily). Not sure where the dark area comes from - maybe a plugin?

![Bildschirmfoto 2021-12-14 um 06 51 05](https://user-images.githubusercontent.com/12938875/145940815-45277b04-ec1c-4330-8057-700332aaa76e.png)

![Bildschirmfoto 2021-12-14 um 06 52 21](https://user-images.githubusercontent.com/12938875/145940957-276fe04b-f614-453a-a25d-3c7ccc80c5ce.png)

**Comment by XinLi0111** [comment]
Thanks for you reply, when I change another theme and changed back, the black strip disappeared. The width of black strip is same as the leftside panel, maybe related to this, but for now, the problem not happen again.

Thanks for your beautiful theme! I love it.
